apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: test-events
  name: pod-patcher
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: attestagon-pod-patcher
  namespace: test-events
subjects:
- kind: ServiceAccount
  name: attestagon
  namespace: test-events
roleRef:
  kind: Role
  name: pod-patcher
  apiGroup: rbac.authorization.k8s.io
