apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: hello-task-run-
  namespace: default
spec:
  workspaces:
    - name: source
      emptyDir: {}
    - name: dockerconfig
      secret:
        secretName: repo-creds
  taskRef:
    name: hello
