apiVersion: apps/v1
kind: Deployment
metadata:
  name: attestagon-controller
  labels:
    app: attestagon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attestagon
  template:
    metadata:
      labels:
        app: attestagon
    spec:
      serviceAccountName: attestagon
      containers:
      - name: controller
        imagePullPolicy: Always
        image: ghcr.io/chaosinthecrd/attestagon/attestagon-a24a1e3a9ccbe312bde6dc43ad61b3a0:latest
        env:
        - name: CONFIG_PATH
          value: /etc/config/config
        - name: DOCKER_CONFIG
          value: /.docker
        - name: COSIGN_KEY
          value: /etc/cosign/cosign.key
        volumeMounts:
        - name: repo-creds
          mountPath: /.docker
        - name: config
          mountPath: /etc/config
        - name: cosign-creds
          mountPath: /etc/cosign
      imagePullSecrets:
      - name: myregistrykey
      volumes:
        - name: cosign-creds
          secret:
            secretName: cosign-creds
            items:
              - key: "cosign.key"
                path: cosign.key
            optional: False
        - name: repo-creds
          secret:
            secretName: repo-creds
            optional: False
        - name: config
          configMap:
            name: attestagon-config
