apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: attestagon
    app.kubernetes.io/name: attestagon
  name: attestagon
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: attestagon
  labels:
    app.kubernetes.io/name: attestagon
    app.kubernetes.io/instance: attestagon
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "watch", "list", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: attestagon
  labels:
    app.kubernetes.io/name: attestagon
    app.kubernetes.io/instance: attestagon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: attestagon
subjects:
- kind: ServiceAccount
  name: attestagon
  namespace: kube-system
