apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "connect"
spec:
  kprobes:
  - call: "tcp_connect"
    syscall: false
    args:
     - index: 0
       type: "sock"
  - call: "tcp_close"
    syscall: false
    args:
     - index: 0
       type: "sock"
---
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "syscalls"
spec:
  kprobes:
  # int setuid(uid_t uid);
  - call: "__x64_sys_setuid"
    syscall: true
    args:
    - index: 0
      type: "int"
---
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "fd-install"
spec:
  kprobes:
  - call: "fd_install"
    syscall: false
    args:
    - index: 0
      type: int
    - index: 1
      type: "file"
---
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "file-write"
spec:
  kprobes:
  - call: "__x64_sys_write"
    syscall: true
    args:
    - index: 0
      type: "fd"
    - index: 1
      type: "char_buf"
      returnCopy: true
    - index: 2
      type: "size_t"
---
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "fs-mount"
spec:
  kprobes:
  - call: "__x64_sys_mount"
    syscall: true
    args:
    - index: 0
      type:  "string"
    - index: 1
      type:  "string"
---
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "file-read"
spec:
  kprobes:
  - call: "__x64_sys_read"
    syscall: true
    args:
    - index: 0
      type: "fd"
    - index: 1
      type: "char_buf"
      returnCopy: true
    - index: 2
      type: "size_t"

