name: Publish

on:
  push:
    branches: ['main']

env:
  KO_DOCKER_REPO: ghcr.io/chaosinthecrd/attestagon

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: actions/checkout@v2

      - uses: imjasonh/setup-ko@v0.4
      - run: ko publish ./
